name             'homeOS'
maintainer       'Pascal Larin'
maintainer_email 'plarin@gmail.com'
license          'All rights reserved'
description      'Installs/Configures homeOS'
long_description 'Installs/Configures homeOS'

version          '0.1.0'

depends 'fail2ban'
depends 'influxdb'
depends 'grafana'
depends 'letsencrypt'
depends 'rabbitmq'
depends 'firewall'
